### ISSUE TITLE
How to add tags to hub registration from PCL?

### ISSUE THREAD

**Issue by pranaykothari** [Daniel-Krzyczkowski/MicrosoftAzure#1]
Hi Daniel, 

Thanks for an awesome video walkthrough of notification hub! Everything works well for Android (tested). However, an important scenario is: user logs in later in the application, and its during that time that we need to add a tag for this specific user to notification hub registration (say tag like uid:54).

We cannot use nuget Microsoft.Azure.NotificationHubs in PCL since it needs .net full profile. So registration with NHub from PCL is getting complicated (although possible with Dependency Injection, RegisterAsync method in each platform projects, and call it after successful login from PCL, in addition to storing the registrationid for android and device token for iOS in settings).

Is there a better way?

**Comment by Daniel-Krzyczkowski** [comment]
Hi!

Thank you for your message. Unfortunately I cannot recommend any other approach than using Dependency Injection on each platform. I think that this approach is the best solution here.

Best regards,
Daniel
