### ISSUE TITLE
Topic Name 

### ISSUE THREAD

**Issue by tomadj** [Daniel-Krzyczkowski/MicrosoftAzure#11]
Hello Daniel, 

Thanks for your article and video on Youtube. 

Should we not pass the topic name ("cars-island-events") in the ServiceBusConnectionStringBuilder ?? 

Thank's 

Thomas 

EDIT : OK, it was necessary to add ";EntityPath=cars-island-events" to the bus connectionstring

**Comment by Daniel-Krzyczkowski** [comment]
Hi Thomas,

Thank you so much for reading the article and reaching out to me.
As you wrote, correct, EntityPath has to be passed in the connection string.
Please let me know if you have any other issues. For now I will close the issue.
